FROM python:3.14-slim

RUN pip install --no-cache-dir poetry

WORKDIR /app

COPY pyproject.toml ./
RUN poetry install --no-root --no-interaction

COPY index_collections.py ./
COPY *.toml ./
COPY ./data/*.tar.gz ./data/