FROM python:3.14-slim

RUN pip install --no-cache-dir poetry

WORKDIR /app

COPY pyproject.toml ./
RUN poetry install --no-root --no-interaction

COPY read_and_index.py ./
COPY *.toml ./
COPY data/ ./data/
CMD tar -zxvf ./data/sport_20260603.tar.gz

ENTRYPOINT ["poetry", "run", "python", "index_collections.py"]
CMD ["./data/sport/ingforms/data"]
