services:
  hi-sportdb-mongo:
    image: registry.diginfra.net/tsd/hi-sportdb-mongo:0.0.1
    volumes:
      - hi-sportdb-mongo-data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh --quiet --eval 'db.adminCommand({ ping: 1 })' > /dev/null" ]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped
    networks:
      - hi-sportdb-net

  hi-sportdb-elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null" ]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - hi-sportdb-es-data:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
          memory: 2g
    restart: unless-stopped
    networks:
      - hi-sportdb-net

  hi-sportdb-panoptes:
    image: registry.diginfra.net/tsd/panoptes-backend:hi-sportdb
    environment:
      - ES_SCHEME=http
      - ES_HOST=bpt-elastic
      - ES_PORT=9200
      - MONGO_CONNECTION=mongodb://hi-sportdb-mongo:27017/
    depends_on:
      bpt-mongo:
        condition: service_healthy
      bpt-elastic:
        condition: service_healthy
    expose:
      - "8000"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.bpt-panoptes.entrypoints=http"
      - "traefik.http.routers.bpt-panoptes.rule=Host(`bataafse-politieke-tijdschriften.sd.di.huc.knaw.nl`) && PathPrefix(`/api`)"
      - "traefik.http.services.bpt-panoptes.loadbalancer.server.port=8000"
    restart: unless-stopped
    networks:
      - hi-sportdb-net
      - traefik-public

  hi-sportdb-browser:
    image: registry.diginfra.net/tsd/hi-sportdb-browser:0.0.1
    environment:
      - VITE_PANOPTES_URL=https://sport.sd.di.huc.knaw.nl
      - VITE_PANOPTES_IS_EMBEDDED=false
      - VITE_PANOPTES_DATASET=sport
      - VITE_PANOPTES_SEARCH_PATH=/$$dataset/search
      - VITE_PANOPTES_DETAIL_PATH=/$$dataset/details/$$id
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.bpt-panoptes-browser.entrypoints=http"
      - "traefik.http.routers.bpt-panoptes-browser.rule=Host(`sport.sd.di.huc.knaw.nl`)"
      - "traefik.http.services.bpt-panoptes-browser.loadbalancer.server.port=80"
    restart: unless-stopped
    networks:
      - hi-sportdb-net
      - traefik-public

  hi-sportdb-indexer:
    image: registry.diginfra.net/tsd/hi-sportdb-indexer:0.0.1
    environment:
      - ES_HOST=hi-sportdb-elastic
      - ES_PORT=9200
    depends_on:
      bpt-elastic:
        condition: service_healthy
    restart: no
    networks:
      - hi-sportdb-net
    tty: true
    stdin_open: true

volumes:
  hi-sportdb-es-data:
  hi-sportdb-mongo-data:

networks:
  hi-sportdb-net:
    internal: true
  traefik-public:
    external: true
