[index]
host="http://localhost:9200"
full_text="yes"
name="hi-sportdb"

[index.input]
format="json"

[index.id]
path="jmes:id"
type="keyword"

[index.facet.sport]
path="jmes:sport"
type="keyword"

[index.facet.naam]
path="jmes:naam"
type="keyword"

[index.facet.alternatieveNamen]
path="jmes:alternatieve_namen"
type="text"

[index.facet.opmerkingNaam]
path="jmes:bronrecords[].naam_opmerking"
type="text"

[index.facet.gemeente1984]
path="jmes:locatie.gemeente_1984_bron"
type="keyword"

[index.facet.plaats]
path="jmes:locatie.plaats_bron"

[index.facet.doelstelling]
path="jmes:vereniging.doelstelling"
type="text"

[index.facet.beginDatumJaar]
path="jmes:begindatum.jaar"
type="number"

[index.facet.beginDatumMaand]
path="jmes:begindatum.maand"
type="number"

[index.facet.beginDatumDag]
path="jmes:begindatum.dag"
type="number"

[index.facet.beginDatumSoort]
path="jmes:begindatum.betekenis"
type="keyword"

[index.facet.eindDatumJaar]
path="jmes:einddatum.jaar"
type="number"

[index.facet.eindDatumSoort]
path="jmes:einddatum.betekenis"
type="keyword"

[index.facet.provincie]
path="jmes:locatie.provincie"
type="keyword"

[index.facet.levensbeschouwing]
path="jmes:levensbeschouwing"
type="keyword"

[index.facet.verantwoordingGegevens]
path="jmes:bronrecords[].verantwoording"
type="text"

[index.facet.werkingsGebied]
path="jmes:werkingsgebied"
type="text"

[index.facet.speeldag]
path="jmes:speeldag"
type="text"

[index.facet.landelijkeBondNaam]
path="jmes:lidmaatschappen[?niveau == 'landelijk'].bondsvermelding"
type="keyword"

[index.facet.regionaleBondNaam]
path="jmes:lidmaatschappen[?niveau == 'regionaal'].bondsvermelding"
type="keyword"

[index.facet.opmerkingen]
path="jmes:bronrecords[].opmerkingen"
type="text"

[index.facet.type]
path="jmes:type"
type="keyword"