[index]
host="http://localhost:9200"
full_text="yes"
name="hi-sportdb"

[index.input]
format="json"

[index.id]
path="jmes:vereniging.id"
type="keyword"

[index.facet.sport]
path="jmes:vereniging.sport.soort_sport"
type="keyword"

[index.facet.naam]
path="jmes:vereniging.naam"
type="keyword"

[index.facet.opmerkingNaam]
path="jmes:vereniging.opm_naam"
type="text"

[index.facet.plaats]
path="jmes:vereniging.gemeente1984"
type="keyword"

[index.facet.doelstelling]
path="jmes:vereniging.doelstelling"
type="text"

[index.facet.beginDatumJaar]
path="jmes:vereniging.begindatum.year"
type="number"

[index.facet.beginDatumMaand]
path="jmes:vereniging.begindatum.month"
type="number"

[index.facet.beginDatumDag]
path="jmes:vereniging.begindatum.day"
type="number"

[index.facet.beginDatumSoort]
path="jmes:vereniging.begindatum_soort"
type="keyword"

[index.facet.eindDatumJaar]
path="jmes:vereniging.einddatum.year"
type="number"

[index.facet.eindDatumSoort]
path="jmes:vereniging.einddatum_soort"
type="keyword"

[index.facet.provincie]
path="jmes:vereniging.provincie.provincie"
type="keyword"

[index.facet.levensbeschouwing]
path="jmes:vereniging.levensbeschouwing"
type="keyword"

[index.facet.verantwoordingGegevens]
path="jmes:vereniging.verantwoording_gegevens"
type="text"

[index.facet.werkingsGebied]
path="jmes:vereniging.werkingsbebied.werkingsgebied"
type="text"

[index.facet.speeldag]
path="jmes:vereniging.speeldag.dag"
type="text"

[index.facet.landelijkeBond]
path="jmes:vereniging.landelijke_bond.Landelijke_bond"
type="nested"

[index.facet.regionaleBond]
path="jmes:vereniging.regionale_bond.Regionale_bond"
type="nested"
